{ config, pkgs, ... }: {

  programs.hyprlock = {
    enable = true;

    settings = {
      # 1. Source Colors (Imperative file generated by Matugen/Wal)
      source = "${config.home.homeDirectory}/.cache/wal/colors-hyprland.conf";

      # 2. General
      general = {
        no_fade_in = false;
        grace = 0;
        disable_loading_bar = true;
      };

      # 3. Backgrounds
      background = [
        {
          monitor = "";
          path = "${config.home.homeDirectory}/.current_wallpaper";
          blur_passes = 2;
          contrast = 0.8916;
          brightness = 0.8172;
          vibrancy = 0.1696;
          vibrancy_darkness = 0.0;
        }
      ];

      # 4. Input Field
      input-field = [
        {
          monitor = "DP-3";
          size = "200, 30";
          outline_thickness = 2;
          dots_size = 0.2;
          dots_spacing = 0.2;
          dots_center = true;
          outer_color = "rgba(0, 0, 0, 0)";
          inner_color = "rgba(0, 0, 0, 0.2)";
          font_color = "rgb(255, 255, 255)";
          fade_on_empty = false;
          font_family = "SF Pro Display Bold";
          placeholder_text = "<i><span foreground=\"##ffffff99\">Enter Password</span></i>";
          hide_input = false;
          position = "0, 80";
          halign = "center";
          valign = "bottom";
        }
      ];

      # 5. Labels
      label = [
        # TIME
        {
          monitor = "DP-3";
          text = ''cmd[update:1000] echo "$(date +"%H:%M")"'';
          color = "rgba(255, 255, 255, 0.6)";
          font_size = 120;
          font_family = "SF Pro Display Bold";
          position = "0, -120";
          halign = "center";
          valign = "top";
        }
        # DATE
        {
          monitor = "DP-3";
          text = ''cmd[update:1000] echo -e "$(date +"%A, %B %d")"'';
          color = "rgba(255, 255, 255, 0.6)";
          font_size = 24;
          font_family = "SF Pro Display Bold";
          position = "0, -100";
          halign = "center";
          valign = "top";
        }
        # WEATHER
        {
          monitor = "DP-3";
          text = "cmd[update:1800000] ${config.home.homeDirectory}/.config/hypr/scripts/weather.sh";
          color = "rgba(255, 255, 255, 0.65)";
          font_size = 18;
          font_family = "JetBrainsMono Nerd Font";
          position = "0, -300";
          halign = "center";
          valign = "top";
        }
        # USER NAME
        {
          monitor = "DP-3";
          text = "$USER";
          color = "rgba(255, 255, 255, 0.8)";
          font_size = 12;
          font_family = "SF Pro Display Bold";
          position = "0, 140";
          halign = "center";
          valign = "bottom";
        }
        # CURRENT SONG
        {
          monitor = "DP-3";
          text = "cmd[update:1000] ${config.home.homeDirectory}/.config/hypr/scripts/songdetail.sh";
          color = "rgba(255, 255, 255, 1.0)";
          font_family = "JetBrainsMono Nerd Font Mono";
          font_size = 28;
          position = "0, 20";
          halign = "center";
          valign = "bottom";
        }
        # DND STATUS
        {
          monitor = "DP-3";
          text = "cmd[update:100] ${config.home.homeDirectory}/.config/hypr/scripts/dnd_status.sh";
          color = "rgba(255, 255, 255, 0.6)";
          font_size = 10;
          font_family = "JetBrainsMono Nerd Font";
          position = "0, -75";
          halign = "center";
          valign = "top";
        }
      ];

      # 6. Profile Photo
      image = [
        {
          monitor = "DP-3";
          path = "~/Profile-Pics/face.png";
          size = 120;
          rounding = -1;
          border_size = 3;
          border_color = "rgba(255, 255, 255, .65)";
          position = "0, 190";
          halign = "center";
          valign = "bottom";
        }
      ];
    };
  };
}
